# Generated by Django 5.1.1 on 2024-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0002_candidat_disponibilite_candidat_gendre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='adresse',
        ),
        migrations.AddField(
            model_name='candidat',
            name='autres_documents',
            field=models.FileField(blank=True, null=True, upload_to='autres_documents/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='compentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_debut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='etablissement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='formation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='iban',
            field=models.CharField(blank=True, max_length=27, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='langues_parlees',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='lettre_motivation',
            field=models.FileField(blank=True, null=True, upload_to='lettres_motivation/'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='notification_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidat',
            name='num_et_rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='preference_lieu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='preference_salaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='profil_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidat',
            name='secu_sociale',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='type_de_contrat_recherche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='type_de_poste_recherche',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/restaurant'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='notification_mail',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='num_et_rue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='site_web',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='disponibilite',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/candidat'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='plage_horaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
