# Generated by Django 5.1.1 on 2024-11-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0003_remove_candidat_adresse_remove_restaurant_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
