# Generated by Django 5.1.1 on 2024-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0005_rename_gendre_candidat_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
