# Generated by Django 5.1.1 on 2024-11-27 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0006_annonce_latitude_annonce_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='salaire_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='salaire_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
