# Generated by Django 5.1.1 on 2024-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0007_candidat_salaire_max_candidat_salaire_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='email_pro',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email_pro',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
