# Generated by Django 5.1.1 on 2024-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0008_candidat_email_pro_restaurant_email_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='avantages',
            field=models.TextField(blank=True, null=True),
        ),
    ]
