# Generated by Django 5.1.1 on 2024-12-03 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0009_annonce_avantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='mode_paiement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='nb_heures_semaine',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
