# Generated by Django 5.1.1 on 2024-12-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0011_annonce_type_annonce_chat_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='date_creation',
            new_name='created_at',
        ),
    ]
