# Generated by Django 5.1.1 on 2024-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0012_rename_date_creation_chat_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
