# Generated by Django 5.1.1 on 2024-12-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0013_chat_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='offre',
            name='annonce',
        ),
        migrations.RemoveField(
            model_name='preferencecandidat',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='preferencerestaurant',
            name='restaurant',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['id'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='compentence',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='type',
        ),
        migrations.AddField(
            model_name='annonce',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='experience',
            field=models.CharField(blank=True, choices=[("Plus d'expereince", "Plus d'expereince"), ("Moins d'expereince", "Moins d'expereince"), ('plus de 1 an', 'plus de 1 an'), ('plus de 2 ans', 'plus de 2 ans'), ('plus de 5 ans', 'plus de 5 ans'), ('plus de 10 ans', 'plus de 10 ans')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='horaire_travail',
            field=models.CharField(blank=True, choices=[('matin', 'Matin : 8h-12h'), ('midi', 'Midi : 12h-15h'), ('soir', 'Soir : 18h-22h'), ('nuit', 'Nuit : 22h-6h')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='jours_de_travail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='type_de_travail',
            field=models.CharField(blank=True, choices=[('servur', 'Serveur'), ('cuisinier', 'Cuisinier'), ('livreur', 'Livreur'), ('netoyage', 'Netoyage'), ('chef', 'Chef'), ('caissier', 'Caissier'), ('plongeur', 'Plongeur'), ('patissier', 'Patissier')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='annonce',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='specilaite',
            field=models.CharField(blank=True, choices=[('serveur', 'Serveur'), ('cuisinier', 'Cuisinier'), ('livreur', 'Livreur'), ('netoyage', 'Netoyage'), ('chef', 'Chef')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ad_cv',
            field=models.FileField(blank=True, null=True, upload_to='candidatures/'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='type_de_restaurant',
            field=models.CharField(blank=True, choices=[('italien', 'Italien'), ('francais', 'Français'), ('chinois', 'Chinois'), ('japonais', 'Japonais'), ('indien', 'Indien'), ('fast_food', 'Fast-food'), ('brasserie', 'Brasserie'), ('toutt', 'Tout')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='disponibilite',
            field=models.TextField(blank=True, choices=[('tout de suite', 'Tout de suite'), ('dans 3 jours', 'Dans 3 jours'), ('dans les prochaines semaines', 'Dans les prochaines semaines'), ('dans les prochains mois', 'Dans les prochains mois')], max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='annonce',
            table='annonce',
        ),
        migrations.AlterModelTable(
            name='candidat',
            table='candidat',
        ),
        migrations.AlterModelTable(
            name='candidature',
            table='candidature',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
        migrations.AlterModelTable(
            name='restaurant',
            table='restaurant',
        ),
        migrations.DeleteModel(
            name='Adresse',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Offre',
        ),
        migrations.DeleteModel(
            name='PreferenceCandidat',
        ),
        migrations.DeleteModel(
            name='PreferenceRestaurant',
        ),
    ]
