# Generated by Django 5.1.1 on 2024-12-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0014_remove_chat_candidat_remove_chat_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='age',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
