# Generated by Django 5.1.1 on 2024-12-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0017_alter_customuser_candidat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='candidat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='restaurant',
        ),
    ]
