# Generated by Django 5.1.1 on 2024-12-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0018_remove_customuser_candidat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='code_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='crenaux_horaire',
            field=models.CharField(blank=True, choices=[('matin', 'Matin : 8h-12h'), ('midi', 'Midi : 12h-15h'), ('soir', 'Soir : 18h-22h'), ('nuit', 'Nuit : 22h-6h')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='disponibilite',
            field=models.TextField(blank=True, choices=[('Lundi', 'Lundi : 8h-30 - 8h-45 - 9h-45'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Tous les jours', 'Tous les jours')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='pays',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='tel',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
