# Generated by Django 5.1.1 on 2024-12-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0019_candidature_code_postal_candidature_crenaux_horaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='jobfiksi_api.restaurant'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='crenaux_horaire',
            field=models.CharField(blank=True, choices=[('8h-12h', 'Matin : 8h-12h'), ('12h-15h', 'Midi : 12h-15h'), ('18h-22h', 'Soir : 18h-22h'), ('22h-6h', 'Nuit : 22h-6h')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='disponibilite',
            field=models.TextField(blank=True, choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Tous les jours', 'Tous les jours')], max_length=100, null=True),
        ),
    ]
