# Generated by Django 5.1.1 on 2024-12-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0020_annonce_restaurant_alter_candidature_crenaux_horaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='restaurant',
        ),
    ]
