# Generated by Django 5.1.1 on 2024-12-11 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0021_remove_annonce_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidature',
            old_name='ad_cv',
            new_name='cv',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='date_debut',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='date_fin',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='etablissement',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='niveau_etude',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='plage_horaire',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='salaire_max',
        ),
        migrations.RemoveField(
            model_name='candidat',
            name='salaire_min',
        ),
        migrations.AddField(
            model_name='annonce',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='note',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='statut',
            field=models.BooleanField(blank=True, choices=[(True, 'Acceptée'), (False, 'Refusée'), (None, 'En attente')], null=True),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='jobfiksi_api.restaurant'),
        ),
        migrations.CreateModel(
            name='CanditatFavoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favori', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='jobfiksi_api.annonce')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='jobfiksi_api.candidat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='jobfiksi_api.restaurant')),
            ],
            options={
                'db_table': 'candidat_favoris',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('type_contrat', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD')], max_length=100, null=True)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('horaire_travail', models.CharField(blank=True, choices=[('temps_plein', 'Temps plein'), ('temps_partiel', 'Temps partiel')], max_length=100, null=True)),
                ('statut', models.CharField(choices=[('signed', 'Signé'), ('not_signed', 'Non signé')], default='not_signed', max_length=10)),
                ('restaurant_comments', models.TextField(blank=True, null=True)),
                ('candidat_comments', models.TextField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='jobfiksi_api.candidat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='jobfiksi_api.restaurant')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'db_table': 'contract',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='jobfiksi_api.candidat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='jobfiksi_api.restaurant')),
            ],
            options={
                'db_table': 'conversation',
            },
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('prévu', 'Prévu'), ('réalisé', 'Réalisé'), ('annulé', 'Annulé')], max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='jobfiksi_api.annonce')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='jobfiksi_api.candidat')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='jobfiksi_api.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceProfessionnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posteOccupe', models.CharField(blank=True, max_length=100, null=True)),
                ('nomStructure', models.CharField(blank=True, max_length=255, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences_professionnelles', to='jobfiksi_api.candidat')),
            ],
            options={
                'db_table': 'experience_professionnelle',
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='experiences',
            field=models.ManyToManyField(blank=True, related_name='candidats_experiences', to='jobfiksi_api.experienceprofessionnelle'),
        ),
        migrations.CreateModel(
            name='FormationsCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveauFormation', models.CharField(blank=True, max_length=100, null=True)),
                ('diplome', models.CharField(blank=True, max_length=100, null=True)),
                ('nomFormation', models.CharField(blank=True, max_length=100, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('dateDebut', models.DateField(blank=True, null=True)),
                ('dateFin', models.DateField(blank=True, null=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations_candidat', to='jobfiksi_api.candidat')),
            ],
            options={
                'db_table': 'formations_candidat',
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='formations',
            field=models.ManyToManyField(blank=True, related_name='candidats_formations', to='jobfiksi_api.formationscandidat'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('type_message', models.CharField(choices=[('text', 'Text'), ('file', 'File')], max_length=10)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='jobfiksi_api.conversation')),
            ],
            options={
                'db_table': 'message',
            },
        ),
        migrations.CreateModel(
            name='FichierJoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='messages/fichiers/')),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('type_fichier', models.CharField(max_length=10)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_joints', to='jobfiksi_api.message')),
            ],
            options={
                'db_table': 'fichier_joint',
            },
        ),
        migrations.CreateModel(
            name='PreferencesCandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flexibilite_deplacement', models.BooleanField(default=False)),
                ('secteur', models.CharField(blank=True, max_length=100, null=True)),
                ('fourchette_salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('type_contrat', models.CharField(blank=True, max_length=100, null=True)),
                ('type_restaurant', models.CharField(blank=True, max_length=100, null=True)),
                ('horaire_travail', models.CharField(blank=True, max_length=100, null=True)),
                ('possibilite_formation', models.BooleanField(default=False)),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences_candidat', to='jobfiksi_api.candidat')),
            ],
            options={
                'db_table': 'preferences_candidat',
            },
        ),
        migrations.AddField(
            model_name='candidat',
            name='preferences',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidat_preferences', to='jobfiksi_api.preferencescandidat'),
        ),
        migrations.CreateModel(
            name='PreferencesRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_etude', models.CharField(blank=True, choices=[('bac', 'Bac'), ('bac+2', 'Bac+2'), ('bac+3', 'Bac+3'), ('bac+5', 'Bac+5'), ('autre', 'Autre')], max_length=100, null=True)),
                ('age_min', models.IntegerField(blank=True, choices=[(18, '18'), (21, '21'), (25, '25'), (30, '30'), (35, '35'), (40, '40')], null=True)),
                ('attente_candidat', models.CharField(blank=True, max_length=255, null=True)),
                ('possibilite_former', models.BooleanField(default=False)),
                ('type_de_contrat', models.CharField(blank=True, choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('intérim', 'Intérim'), ('stage', 'Stage')], max_length=100, null=True)),
                ('type_de_travail', models.CharField(blank=True, choices=[('serveur', 'Serveur'), ('cuisinier', 'Cuisinier'), ('livreur', 'Livreur'), ('nettoyage', 'Nettoyage'), ('chef', 'Chef'), ('caissier', 'Caissier'), ('plongeur', 'Plongeur'), ('patissier', 'Patissier')], max_length=100, null=True)),
                ('possibilite_debuter', models.BooleanField(default=False)),
                ('horaire_travail', models.CharField(blank=True, choices=[('matin', 'Matin'), ('midi', 'Midi'), ('soir', 'Soir'), ('nuit', 'Nuit'), ('flexible', 'Flexible')], max_length=100, null=True)),
                ('creneau_1', models.DateTimeField(blank=True, null=True)),
                ('creneau_2', models.DateTimeField(blank=True, null=True)),
                ('creneau_3', models.DateTimeField(blank=True, null=True)),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='jobfiksi_api.restaurant')),
            ],
            options={
                'db_table': 'preferences_restaurant',
            },
        ),
    ]
