# Generated by Django 5.1.1 on 2024-12-13 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0023_rename_fichierjoint_fichierjointmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='user',
        ),
        migrations.AlterField(
            model_name='annonce',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to=settings.AUTH_USER_MODEL),
        ),
    ]
