# Generated by Django 5.1.1 on 2024-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0025_remove_candidat_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='niveau_etude',
            field=models.CharField(blank=True, choices=[('bac', 'Bac'), ('bac+2', 'Bac+2'), ('bac+3', 'Bac+3'), ('bac+5', 'Bac+5'), ('autre', 'Autre')], max_length=100, null=True),
        ),
    ]
