# Generated by Django 5.1.1 on 2024-12-15 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0027_candidat_nationalite_alter_candidat_disponibilite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='experiences',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='formations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
