# Generated by Django 5.1.1 on 2024-12-16 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0028_alter_candidat_experiences_alter_candidat_formations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationscandidat',
            name='candidat',
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['date_envoi']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='candidat',
            field=models.ForeignKey(limit_choices_to={'user_type': 'candidat'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_candidat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='restaurant',
            field=models.ForeignKey(limit_choices_to={'user_type': 'restaurant'}, on_delete=django.db.models.deletion.CASCADE, related_name='conversations_restaurant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fichierjointmessage',
            name='type_fichier',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='contenu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type_message',
            field=models.CharField(choices=[('text', 'Text'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('candidat', 'restaurant')},
        ),
        migrations.DeleteModel(
            name='ExperienceProfessionnelle',
        ),
        migrations.DeleteModel(
            name='FormationsCandidat',
        ),
    ]
