# Generated by Django 5.1.1 on 2024-12-16 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0029_remove_formationscandidat_candidat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='type_message',
        ),
        migrations.AddField(
            model_name='conversation',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='conversations/fichiers/'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='messages/fichiers/'),
        ),
        migrations.DeleteModel(
            name='FichierJointMessage',
        ),
    ]
