# Generated by Django 5.1.1 on 2024-12-16 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobfiksi_api', '0030_remove_message_type_message_conversation_fichier_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together=set(),
        ),
    ]
